all: cst ast nominal-subtyping structural-subtyping
cst :
	dot -Tsvg cst.dot -o cst.svg
ast :
	dot -Tsvg ast.dot -o ast.svg
nominal-subtyping :
	dot -Tsvg nominal-subtyping.dot -o nominal-subtyping.svg
structural-subtyping :
	dot -Tsvg structural-subtyping.dot -o structural-subtyping.svg
